Enable ID queues full bandwidth feature through parameter.
pulp-platform/axi_riscv_atomics pull request #33
Opened 2024-04-17 05:47 UTC by yvantor

2024-04-30 06:54 UTC, SamuelRiedel requested changes
Thanks. Generally, it looks good to me, but could you change the default to 1 to not change the default for other designs?

2024-05-08 07:52 UTC, yvantor commented
> Thanks. Generally, it looks good to me, but could you change the default to 1 to not change the default for other designs?

Should be done, thank you!

2024-05-08 09:02 UTC, SamuelRiedel requested changes

2024-05-08 09:02 UTC, SamuelRiedel commented on src/axi_riscv_atomics_structs.sv
> +  parameter bit           FullBandwidth   = 0,
Thanks. Could you please also change the default here? Then, we can merge.

2024-05-08 10:06 UTC, yvantor commented on src/axi_riscv_atomics_structs.sv
> +  parameter bit           FullBandwidth   = 0,
Sorry, should be fixed!

2024-05-08 10:11 UTC, SamuelRiedel approved these changes

2024-05-08 10:12 UTC, merged